projects:
  app:
    schemaPath: ./src/schema.graphql
    extensions:
      endpoints:
        default: http://178.128.182.29:4000
  database:
    schemaPath: ./src/generated/prisma.graphql
    extensions:
      prisma: ./database/prisma.yml
